### ISSUE TITLE
Imlib2 Developer Warning

### ISSUE THREAD

**Issue by jdietrch** [trizen/obmenu-generator#34]
I noticed that the following message is repeated very many times in my .xsession-errors file:
```
***** Imlib2 Developer Warning ***** :
        This program is calling the Imlib call:

        imlib_free_image();

        With the parameter:

        image

        being NULL. Please fix your program.
ObRender-Message: Cannot load image "" from file ""
```

I found out that three of those messages were being produced each time I right-clicked on the desktop background to bring up the openbox menu.

Further investigation showed that two of those messages were due to the fact that two of the .desktop files in /usr/share/applications specified no icon. In other words, those two .desktop files have no line that begins with `Icon=`.

**Question 1:** For .desktop files like these, that don't specify an icon, would it be possible for obmenu-generator to not produce these messages?

The other one of those three was due to this line in my schema.pl:
```
{item => ['gsimplecal',       'Show/Hide Calendar', undef]},
```
**Question 2:** Is there a way to specify no icon in a line like that, in a way that doesn't produce the aforementioned error message?

Thank you!

James

**Comment by trizen** [comment]
Thanks for reporting. This should be fixed in the above commit.

**Comment by jdietrch** [comment]
Thanks for working on this!

However, the above commit only addresses "Question 2" above. It does not address "Question 1", which is the case of .desktop files that have not specified an icon. In other words, these are .desktop files that have no line that begins with `Icon=`. And so I still get two of the following message every time I right-click on the desktop background to bring up the openbox menu because I have two .desktop files that don't specify an icon:
```
***** Imlib2 Developer Warning ***** :
        This program is calling the Imlib call:

        imlib_free_image();

        With the parameter:

        image

        being NULL. Please fix your program.
ObRender-Message: Cannot load image "" from file ""

```

**Question:** For .desktop files like these, that don't specify an icon, would it be possible for obmenu-generator to not produce these messages?

Thank you!

James

**Comment by trizen** [comment]
When the `Icon` key is  not specified, the value would be undefined, hence the above commit takes care of this as well.

Try to remove the cache first:

```
obmenu-generator -d
```

**Comment by jdietrch** [comment]
Short version:
I ran the command `obmenu-generator -d` but I still get two of those errors every time I right-click the desktop background.

Longer version, with more information:
Here is my `.config/openbox/menu.xml`: (to show what command is being run to generate the menu)
```
jdietrch@saturn:~$ cat .config/openbox/menu.xml
<?xml version="1.0" encoding="utf-8"?>
<openbox_menu xmlns="http://openbox.org/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://openbox.org/">
    <menu id="root-menu" label="obmenu-generator" execute="/home/jdietrch/bin/obmenu-generator -i" />
</openbox_menu>
jdietrch@saturn:~$
```
Here is the md5sum of `/home/jdietrch/bin/obmenu-generator`: (to show that I'm running the updated version)
```
jdietrch@saturn:~$ md5sum /home/jdietrch/bin/obmenu-generator
2493f0d7b042b6c7a28c571614bcf236  /home/jdietrch/bin/obmenu-generator
jdietrch@saturn:~$
```
And so I run `obmenu-generator -d`: (I have snipped out most of the lines it prints.)
```
jdietrch@saturn:~$ obmenu-generator -d
<openbox_pipe_menu>
[snip many lines]
</openbox_pipe_menu>
jdietrch@saturn:~$
```
Next I empty the .xsession-errors file:
```
jdietrch@saturn:~$ > .xsession-errors
jdietrch@saturn:~$ cat .xsession-errors
jdietrch@saturn:~$
```
At this point I right-click on the desktop background. And then .xsession-errors contains the following:
```
jdietrch@saturn:~$ cat .xsession-errors
:: Regenerating the cache DB...
Too late to run INIT block at /usr/lib/x86_64-linux-gnu/perl5/5.32/Glib/Object/Introspection.pm line 257.
***** Imlib2 Developer Warning ***** :
        This program is calling the Imlib call:

        imlib_free_image();

        With the parameter:

        image

        being NULL. Please fix your program.
ObRender-Message: Cannot load image "" from file ""
***** Imlib2 Developer Warning ***** :
        This program is calling the Imlib call:

        imlib_free_image();

        With the parameter:

        image

        being NULL. Please fix your program.
ObRender-Message: Cannot load image "" from file ""
jdietrch@saturn:~$
```
After this, as root, I temporarily moved the two .desktop files with no icon specified from `/usr/share/applications` to `/root`. Then right-clicking on the desktop does not produce those errors anymore. That's how I know those errors are being caused by those two .desktop files. Here is the contents of one of them:
```
root@saturn:/usr/share/applications# cat /root/texdoctk.desktop
[Desktop Entry]
Name=TeXdoctk
Exec=texdoctk
Type=Application
Terminal=false
Comment=Display TeX related documentation
Categories=Settings;
root@saturn:/usr/share/applications#
```

So, I must be missing something, but I can't seem to figure out what it is.

Thank you for your help.

James

**Comment by trizen** [comment]
Sorry, you're right. I missed one case in the previous commit. Should be fixed now:

```console
perl obmenu-generator -i | grep -i texdoctk
```

now produces the following output:

```xml
    <item label="TeXdoctk"><action name="Execute"><command><![CDATA[texdoctk]]></command></action></item>
```

**Comment by jdietrch** [comment]
That took care of it. Thank you!
